apiVersion: "example.delivion.de/v1alpha1"
kind: "Application"
metadata:
  name: "app1"
  namespace: "default"
spec:
  database:
    enable: True
    spec: 
      disksize: "1Gi"
      clustersize: 2
      configmap:
        metadata:
          name: pgconfig
        data:
          POSTGRES_DB: dbDE123
      secret:
        metadata:
          name: pgsecret
        stringData:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: pwd
  externalsecret: 
    url: https://jsontest139.000webhostapp.com/a2.json
    reload: False
  replicas: 3
  template:
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: nginx
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80