apiVersion: "example.delivion.de/v1alpha1"
kind: "Application"
metadata:
  name: "app2"
  namespace: "default"
spec:
  database:
    enable: True
    spec: 
      disksize: "1Gi"
      clustersize: 1
      configmap:
        metadata:
          name: pgconfig2
        data:
          POSTGRES_DB: dbBusy
      secret:
        metadata:
          name: pgsecret2
        stringData:
          POSTGRES_USER: adminbox
          POSTGRES_PASSWORD: pwdbox
  externalsecret: 
    url: https://jsontest139.000webhostapp.com/a1.json
    reload: False
  replicas: 2
  template:
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']