apiVersion: "example.delivion.de/v1alpha1"
kind: "Application"
metadata:
  name: "test3"
  namespace: "default"
spec:
  database:
    enable: True
    spec: 
      disksize: "1Gi"
      clustersize: 1
      secret:
        metadata:
          name: pgsecret2
        stringData:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: pwd    
  externalsecret: 
    url: https://jsontest139.000webhostapp.com/a2.json
    reload: False
  replicas: 1
  template:
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']