apiVersion: "example.delivion.de/v1alpha1"
kind: "Application"
metadata:
  name: "app1"
  namespace: "default"
spec:
  database:
    enable: True
    spec: 
      disksize: "1Gi"
      clustersize: 1
      secret:
          metadata:
            name: pgsecret12345
          stringData:
            POSTGRES_USER: admin12
            POSTGRES_PASSWORD: pwd12
  externalsecret: 
    url: https://jsontest139.000webhostapp.com/a1.json
    reload: False
  replicas: 1
  template:
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: nginx
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80