apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "applications.example.delivion.de"
spec:
  group: "example.delivion.de"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "applications"
    singular: "application"
    kind: "Application" 
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["replicas"]
          properties:
            replicas:
              type: "integer"
              minimum: 1