apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nodeingress
spec:
  tls:
  - hosts:
    - node.delivion.de
    secretName: tls-secret
  rules:
  - host: node.delivion.de
    http: 
      paths:
      - path: /
        backend:
            serviceName: node-clusterip
            servicePort: 80