apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: apps-controller
rules:

- apiGroups: ["example.delivion.de"]  
  resources: ["applications"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
- apiGroups: ["apps"] 
  resources: ["deployments","statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps", "secrets", "services"]
  verbs: ["get", "list", "create", "update", "delete"]