apiVersion: apps/v1
kind: Deployment
metadata:
  name: appscontroler-dep
  labels:
    app: appsctr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appsctr
  template:
    metadata:
      labels:
        app: appsctr
    spec:
      serviceAccountName: controller-service-account
      automountServiceAccountToken: true
      containers:
      - image: thaihoang/appscontroller:main-1ba77b7
        imagePullPolicy: IfNotPresent
        name: appsctr
        resources:
          limits:
            memory: 512Mi
            cpu: "1"